I’m a senior engineer at [[https://github.com][GitHub]]. I work on the Semantic Code team, where I play a part in maintaining the open-source project [[http://github.com/github/semantic][~semantic~]], a toolkit for programming language analysis and interpretation.

I was born in Limerick, Ireland. My parents immigrated to the United States when I was very young. I've lived in seven different states, but New York City is my home. I’ve been programming since I was ten years old, and I’ve been a professional programmer since I was eighteen. (It’s the only job I've ever had.) I started my career at Apple, where I worked on macOS (10.5 through 10.7) and the iWork suite; I left in 2014 to work for a series of startups, where I started writing Haskell professionally.

I’m passionate about a great many things in life. Here is an inexhaustive list thereof:

- *Programming languages.* Programming languages lie at the intersection between the binary, deterministic, silicon world of computers and the inexact, chaotic, organic world of human consciousness and communication. I believe that all programming languages, no matter how strange or quirky, are worthy expressions of human creativity and expression. I am driven to understand the history and historical impact of programming languages, the capabilities of the languages I use for work and play, and modern developments in programming language theory that will determine the course of future languages.
- *Functional programming.* FP is an inexact concept, one that means many things to many people. To me, functional programming is the practice of applying mathematical formalisms to real-world programming problems. My experience in industry has convinced me that a declarative, rather than imperative, approach to program design makes it easier to deliver reliable, predictable software artifacts to the world at large. I use the functional programming language [[https://en.wikipedia.org/wiki/Haskell_(programming_language)][Haskell]] to provide me with an elegant and powerful vocabulary for expression functional programs.
- *Open source.* I contribute to several open-source projects, the most notable of which are [[http://github.com/github/semantic][~semantic~]] and [[https://github.com/fused-effects][~fused-effects~]], an effect system for Haskell. I also work on [[https://github.com/patrickt][a bunch of other projects]]. Though I don’t think that an open-source license makes a piece of software /a priori/ good, I think that open-source can and should be used to marshal against the effects of capitalism. I care about the [[https://ethicalsource.dev][evolution of ethical software licenses]].
- *Emacs*. I think that [[https://en.wikipedia.org/wiki/Emacs][Emacs]], for all its flaws, is one of the great achievements in all software. I spend all day inside Emacs and have spent more than a decade fine-tuning [[https://github.com/patrickt/emacs][my setup]].
- *Mental health advocacy.* I live with type-1 bipolar disorder. Mine is well-managed, but I believe it’s a moral imperative to provide free, universally-accessible mental health (and physical health) treatment to everyone who needs it.
- *Rap.* I owe much of who I am to the visionaries and luminaries who’ve used their music to give me a window into their world.

** Nerd Stuff

The posts on this blog are licensed under the Creative Commons [[https://creativecommons.org/licenses/by-nc-sa/4.0/][BY-NC-SA 4.0]] license. I built this blog using [[https://jaspervdj.be/hakyll/][Hakyll]], [[https://orgmode.org][Org-mode]], [[https://github.com/edwardtufte/tufte-css][Edward Tufte’s CSS]], and [[https://pages.github.com][GitHub Pages]]. You can take a look at [[https://github.com/patrickt/patrickt.github.io][the source]] if you’re curious as to how it works. There is no support for comments on this blog, as all its pages are statically generated; if you truly feel compelled to comment, there are many news aggregators that provide you with such a space.

This blog’s domain name, a weak pun on [[https://en.wikipedia.org/wiki/Tagged_union][sum types]] and a [[https://www.youtube.com/watch?v=-KKbdErJkiY][good song]], was coined by Andy Gross (1977-2018).
