name: Build and deploy to GitHub Pages
on: push

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      GHC_VERSION: '8.10.2'
      CABAL_VERSION: '3.4'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{env.GHC_VERSION}}
          cabal-version: ${{env.CABAL_VERSION}}

      - run: cabal update
      - run: cabal build --only-dependencies

      - uses: actions/cache@v2
        with:

          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: cabal build
      - run: cabal exec organic build

      - name: 'Run peaceiris/actions-gh-pages@v2.5.0: deploy to github pages'
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: _site
          EXTERNAL_REPOSITORY: patrickt/patrickt.github.io
        if: github.ref == 'refs/heads/develop'
