name: Build and deploy to GitHub Pages
on: push

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      GHC_VERSION: '8.10.2'
      CABAL_VERSION: '3.4'

    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@2.0.0

      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{env.GHC_VERSION}}
          cabal-version: ${{env.CABAL_VERSION}}

      - name: 'Run actions/cache@v1: cache cabal store'
        uses: actions/cache@v1
        with:
          path: ~/.cabal/store
          key: cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-
            cabal-store-${{ runner.OS }}-

      - run: cabal update
      - run: cabal build --only-dependencies
      - run: cabal build
      - run: cabal exec organic build

      - name: 'Run peaceiris/actions-gh-pages@v2.5.0: deploy to github pages'
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: _site
          EXTERNAL_REPOSITORY: patrickt/patrickt.github.io
        if: github.ref == 'refs/heads/develop'
